//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccentureAccademySchultenAlejandro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscritoPor
    {
        public int Id_EscritoPor { get; set; }
        public int Id_Libro { get; set; }
        public int Id_Autor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
